apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:3.1.4
          command: ["python3"]
          args: ["-m", "mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-artifacts
              mountPath: ./artifacts
      volumes:
        - name: mlflow-artifacts
          emptyDir: {}
